name: Build SherpaOnnx WebAssembly

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scripts/build-sherpaonnx-wasm.sh'
      - '.github/workflows/build-sherpaonnx-wasm.yml'

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.53
          actions-cache-folder: 'emsdk-cache'
      
      - name: View emsdk version
        shell: bash
        run: |
          emcc -v
          echo "--------------------"
          emcc --check
      
      - name: Build SherpaOnnx WebAssembly
        shell: bash
        run: |
          chmod +x scripts/build-sherpaonnx-wasm.sh
          ./scripts/build-sherpaonnx-wasm.sh
      
      - name: Upload WebAssembly files
        uses: actions/upload-artifact@v4
        with:
          name: sherpaonnx-wasm
          path: public/sherpaonnx-wasm/
      
      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: sherpaonnx-wasm-tarball
          path: sherpa-onnx/sherpa-onnx-wasm-simd-*.tar.bz2
