name: Bundle Smoke

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'dist/**'
      - 'package.json'
      - '.github/workflows/bundle-smoke.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'dist/**'
      - 'package.json'
      - '.github/workflows/bundle-smoke.yml'

jobs:
  bundle-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name: Build dist
        run: npm run build
      - name: Run bundler smoke test (rollup)
        run: npm run smoke:bundle

