name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - run: npm ci
    # Install peer dependencies for build
    - name: Install peer dependencies
      run: |
        # Install all cloud dependencies for build and testing
        npm install js-tts-wrapper@file:$GITHUB_WORKSPACE[cloud]
        # Install SherpaOnnx dependencies except the platform-specific binary
        npm install decompress@^4.2.1 decompress-bzip2@^4.0.0 decompress-tarbz2@^4.1.1 decompress-targz@^4.1.1 tar-stream@^3.1.7
    - run: npm run build
    - run: npm run lint
    - run: npm test
    # We don't run TTS tests on PRs since they require credentials
